### ISSUE TITLE
Run without STT or Wake Word Detection?

### ISSUE THREAD

**Issue by ShawnHymel** [OpenVoiceOS/OVOS-local-backend#15]
I have Mycroft (Picroft) configured to use Mozilla DeepSpeech (for STT) and Mozilla TTS (each running as a separate service on another network-connected computer). I'm using Precise (locally on the Pi) to perform wake word detection.

Is there a way to disable STT and wake word detection on the local backend? I don't need either of those, as I'm using DeepSpeech and TTS.

Additionally, I'm getting the following error when I try to run the backend. I'm assuming I need to pip install speech_recognition, but I'd rather find a way to disable STT on the local backend if I intend to provide my own STT server.

```
$ ovos-local-backend      Traceback (most recent call last):
  File "/home/sgmustadio/Projects/ovos-local-backend/ovos-venv/bin/ovos-local-backend", line 8, in <module>
    sys.exit(main())
  File "/home/sgmustadio/Projects/ovos-local-backend/ovos-venv/lib/python3.6/site-packages/ovos_local_backend/__main__.py", line 14, in main
    start_backend(args.flask_port, args.flask_host)
  File "/home/sgmustadio/Projects/ovos-local-backend/ovos-venv/lib/python3.6/site-packages/ovos_local_backend/backend/__init__.py", line 51, in start_backend
    app = create_app()
  File "/home/sgmustadio/Projects/ovos-local-backend/ovos-venv/lib/python3.6/site-packages/ovos_local_backend/backend/__init__.py", line 27, in create_app
    from ovos_local_backend.backend.stt import get_stt_routes
  File "/home/sgmustadio/Projects/ovos-local-backend/ovos-venv/lib/python3.6/site-packages/ovos_local_backend/backend/stt.py", line 25, in <module>
    from speech_recognition import Recognizer, AudioFile
ModuleNotFoundError: No module named 'speech_recognition'
```

**Comment by ShawnHymel** [comment]
Nevermind, I misunderstood how this service is supposed to run (on device rather than on a separate server). That's what I get for trying to read the documentation when I'm tired :)
