### ISSUE TITLE
Cannot get local backend to work without Internet connection

### ISSUE THREAD

**Issue by ShawnHymel** [OpenVoiceOS/OVOS-local-backend#16]
First, the default config in the README gives me an error:

```
Traceback (most recent call last):
  File "/home/pi/mycroft-core/.venv/bin/ovos-local-backend", line 8, in <module>
    sys.exit(main())
  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/ovos_local_backend/__main__.py", line 14, in main
    start_backend(args.flask_port, args.flask_host)
  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/ovos_local_backend/backend/__init__.py", line 51, in start_backend
    app = create_app()
  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/ovos_local_backend/backend/__init__.py", line 27, in create_app
    from ovos_local_backend.backend.stt import get_stt_routes
  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/ovos_local_backend/backend/stt.py", line 28, in <module>
    engine = OVOSSTTFactory.create(CONFIGURATION["stt"])
  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/ovos_plugin_manager/stt.py", line 75, in create
    plugin_config = config[plugin]
KeyError: 'google'
```

When I update the key/value to `"stt": {"module": "google", "google": {}},`, that seems to work. The server boots up on my Pi.

Here is my /tmp/mycroft.json config file (should be the same as in the README):

```
{
    "server": {
        "url": "http://0.0.0.0:6712",
        "version": "v1",
        "update": true,
        "metrics": true
      },
    "tts": {
      "module":"mimic2",
          "mimic2": {
              "url": "http://0.0.0.0:6712/synthesize/mimic2/kusal/en?text="
      }
   },
   "listener": {
        "wake_word_upload": {
            "url": "http://0.0.0.0:6712/precise/upload"
        }
    }
}
```

When I load Mycroft, I can see the connection to the local backend:

```
(.venv) pi@picroft:~/mycroft-core/.venv/bin $ ovos-local-backend
 * Serving Flask app 'ovos_local_backend.backend' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:6712 (Press CTRL+C to quit)
127.0.0.1 - - [12/Apr/2022 21:55:40] "GET /v1/device/c49f6588-90eb-4acc-a55d-135e3541e06f HTTP/1.1" 200 -
127.0.0.1 - - [12/Apr/2022 21:55:40] "GET /v1/device/c49f6588-90eb-4acc-a55d-135e3541e06f/setting HTTP/1.1" 200 -
127.0.0.1 - - [12/Apr/2022 21:55:40] "GET /v1/device/c49f6588-90eb-4acc-a55d-135e3541e06f/location HTTP/1.1" 200 -
```

However, Mycroft cannot find Precise for wake word detection, so it defaults to PocketSphinx:

```
2022-04-12 21:58:18.096 | INFO     | 15916 | mycroft.client.speech.hotword_factory:load_module:500 | Loading "hey mycroft" wake word via pocketsphinx
2022-04-12 21:58:18.127 | ERROR    | 15916 | mycroft.client.speech.hotword_factory:update_precise:270 | Precise could not be downloaded(ConnectionError(MaxRetryError("HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /MycroftAI/precise-data/raw/dist/armv7l/latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x733ec290>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))")))
2022-04-12 21:58:18.284 | INFO     | 15916 | mycroft.client.speech.listener:create_wakeup_recognizer:365 | creating stand up word engine
2022-04-12 21:58:18.287 | INFO     | 15916 | mycroft.client.speech.hotword_factory:load_module:500 | Loading "wake up" wake word via pocketsphinx
2022-04-12 21:58:18.404 | INFO     | 15916 | __main__:on_ready:179 | Speech client is ready.
```

It also fails to find mimic2 for TTS:

```
2022-04-12 21:58:07.077 | INFO     | 15888 | mycroft.audio.audioservice:get_services:63 | Loading services from /home/pi/mycroft-core/mycroft/audio/services/
2022-04-12 21:58:07.082 | INFO     | 15888 | mycroft.audio.audioservice:load_internal_services:135 | Loading chromecast
2022-04-12 21:58:15.294 | INFO     | 15888 | mycroft.audio.audioservice:load_internal_services:135 | Loading mopidy
2022-04-12 21:58:15.304 | INFO     | 15888 | mycroft.audio.audioservice:load_internal_services:135 | Loading mplayer
2022-04-12 21:58:15.388 | ERROR    | 15888 | audioservice_mplayer:<module>:20 | install py_mplayer with pip install git+https://github.com/JarbasAl/py_mplayer
2022-04-12 21:58:15.390 | ERROR    | 15888 | mycroft.audio.audioservice:load_internal_services:144 | Failed to import module mplayer
ModuleNotFoundError("No module named 'py_mplayer'")
2022-04-12 21:58:15.393 | INFO     | 15888 | mycroft.audio.audioservice:load_internal_services:135 | Loading simple
2022-04-12 21:58:15.407 | INFO     | 15888 | mycroft.audio.audioservice:load_internal_services:135 | Loading vlc
2022-04-12 21:58:15.526 | ERROR    | 15888 | mycroft.audio.audioservice:setup_service:112 | Failed to load service. NameError("no function 'libvlc_new'")
2022-04-12 21:58:15.575 | INFO     | 15888 | mycroft.audio.audioservice:load_services:235 | Finding default backend...
2022-04-12 21:58:15.577 | INFO     | 15888 | mycroft.audio.audioservice:load_services:239 | Found local
2022-04-12 21:58:15.683 | INFO     | 15888 | __main__:on_ready:33 | Audio service is ready.
2022-04-12 21:58:44.872 | INFO     | 15888 | mycroft.audio.speech:mute_and_speak:127 | Speak: This unit is not connected to the Internet. Either plug in a network cable or setup your wifi connection.
2022-04-12 21:58:49.900 | ERROR    | 15888 | mycroft.audio.speech:mute_and_speak:131 | Mimic 2 server request timed out. Falling back to mimic
2022-04-12 21:58:49.913 | WARNING  | 15888 | mycroft.tts.tts:clear_cache:428 | This method is deprecated, use TextToSpeechCache.clear
```

 Finally, Mycroft just spins looking for DNS server:

```
 21:56:36.484 | ERROR    | 15024 | mycroft.util.network_utils:_connected_dns:78 | Unable to connect to secondary DNS server.
 21:56:46.503 | ERROR    | 15024 | mycroft.util.network_utils:_connected_ncsi:46 | Unable to verify connection via NCSI endpoint.
 21:56:50.512 | ERROR    | 15024 | mycroft.util.network_utils:_connected_dns:69 | Unable to connect to primary DNS server, trying secondary...
 21:56:53.519 | ERROR    | 15024 | mycroft.util.network_utils:_connected_dns:78 | Unable to connect to secondary DNS server.
```

I cannot issue any commands--it won't recognize the wake word. Any idea on how to get this working with a Pi completely disconnected from the Internet?

**Comment by JarbasAl** [comment]
Hello there, apologies for the late response

The issue you are running into is a known limitation on mycroft-core and by design, mycroft-core is very tightly coupled to the home backend and had hardcoded checks for internet connection in a few places, while the local backend can replace selene it can not bypass these checks, so the device needs internet even if it doesnt use it

Some skills require internet (wolfram, weather, wikipedia....) so these checks are not totally unwarranted

You may want to check ovos-core, it runs fully offline and you don't even need the local backend for that!
